name: Publish to GitHub Packages

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Критически важно!
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: |
          ./gradlew publish \
            -Pgpr.user=${{ github.repository_owner }} \
            -Pgpr.key=${{ secrets.GH_PACKAGES_TOKEN }} \
            --no-daemon \
            --stacktrace
